services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://db:27017/recipes
    depends_on:
      - db

  db:
    image: mongo:7.0
    ports:
      - "27017:27017"
